global:
  scrape_interval: 5s # Scrape often so we see updates quickly

scrape_configs:
  - job_name: 'sre-app'
    static_configs:
      - targets: ['app:8000'] # 'app' is the hostname we will define in Docker Compose
